spring.application.name=ecosphere-backend

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/ecosphere_db
spring.datasource.username=root
spring.datasource.password=password
cloudinary.cloud-name=dsmotu3im
cloudinary.api-key=849676111424481
cloudinary.api-secret=51ogkLQwN0PJ6NKcY9YO-uqEMZI

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cse.karan2007@gmail.com
spring.mail.password=blny wgzc ixvm chcl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080